name: Go Run Test

on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'master'
    tags:       # tag更新时触发此workflow
      - 'v*'

jobs:
  my_build_job:  # job的名字
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          docker pull firekylin93/go-app:latest
          docker run -i firekylin93/go-app
          docker ps -a
          docker exec firekylin93/go-app /bin/bash -c "app -name firekylin"